# Project
version               = 1.3.1
group                 = brightspark.asynclocator

# Common
minecraft_version     = 1.21.1
# Forge - https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version         = 52.1.1

# Neoforge - https://neoforged.net/page/2/
neoforge_version      = 21.1.80

# Fabric - https://fabricmc.net/develop/
fabric_version        = 0.116.1+1.21.1
fabric_loader_version = 0.16.14

# Mod options
mod_name              = async-locator
mod_author            = bright_spark,aleosiss
mod_id                = asynclocator

# Gradle
org.gradle.jvmargs    = -Xmx3G
org.gradle.daemon     = false

parchment_minecraft=1.21
parchment_version=2024.11.10

# kotlin
kotlin_version        = 2.1.21
fabric_kotlin_version = 1.13.3+kotlin.2.1.21
forge_kotlin_version  = 5.8.0

# Multiloader template additions
java_version=21
license= MIT
credits=BrightSpark
description=Asynchronius Locate Command for Minecraft 1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
forge_loader_version_range=[52,)
neoforge_loader_version_range=[4,)
